//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Strings.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AntiSpamResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AntiSpamResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DiscordApi.Resources.Extensions.AntiSpamResources", typeof(AntiSpamResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulk deleted spam by {0}:.
        /// </summary>
        internal static string deleted_spam_title {
            get {
                return ResourceManager.GetString("deleted_spam_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muted user {0} &lt;@{1}&gt; for spamming..
        /// </summary>
        internal static string user_muted_text {
            get {
                return ResourceManager.GetString("user_muted_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Muted for Spamming..
        /// </summary>
        internal static string user_muted_title {
            get {
                return ResourceManager.GetString("user_muted_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timed out user {0} &lt;@{1}&gt; for spamming (3 Days)..
        /// </summary>
        internal static string user_timedout_text {
            get {
                return ResourceManager.GetString("user_timedout_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Timed Out for Spamming..
        /// </summary>
        internal static string user_timedout_title {
            get {
                return ResourceManager.GetString("user_timedout_title", resourceCulture);
            }
        }
    }
}
