//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Strings.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ModnoteResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ModnoteResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Strings.Resources.ModnoteResources", typeof(ModnoteResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Modnote at {0] for {1}..
        /// </summary>
        internal static string error_id_mismatch {
            get {
                return ResourceManager.GetString("error_id_mismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are missing the required permissions to access this command..
        /// </summary>
        internal static string error_missing_permissions {
            get {
                return ResourceManager.GetString("error_missing_permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error. Modnotes are not enabled for this server..
        /// </summary>
        internal static string error_not_enabled {
            get {
                return ResourceManager.GetString("error_not_enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modnote created for user {0} &lt;@{1}&gt;..
        /// </summary>
        internal static string modnote_created {
            get {
                return ResourceManager.GetString("modnote_created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modnote created by {0} &lt;@{1}&gt; for  {2} &lt;@{3}&gt;..
        /// </summary>
        internal static string modnote_log_title {
            get {
                return ResourceManager.GetString("modnote_log_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modnotes for {0}.
        /// </summary>
        internal static string modnote_overview_title {
            get {
                return ResourceManager.GetString("modnote_overview_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modnote {0} for {1} - logged by {2} on {3}..
        /// </summary>
        internal static string modnote_view_title {
            get {
                return ResourceManager.GetString("modnote_view_title", resourceCulture);
            }
        }
    }
}
