//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiscordApi.Resources.Extensions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LoggingResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LoggingResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DiscordApi.Resources.Extensions.LoggingResources", typeof(LoggingResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days..
        /// </summary>
        internal static string days {
            get {
                return ResourceManager.GetString("days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours..
        /// </summary>
        internal static string hours {
            get {
                return ResourceManager.GetString("hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message by user {0} &lt;@{1}&gt; \n was deleted in channel &lt;#{2}&gt; \n **Content:** \n {3}.
        /// </summary>
        internal static string message_deleted_text {
            get {
                return ResourceManager.GetString("message_deleted_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message deleted..
        /// </summary>
        internal static string message_deleted_title {
            get {
                return ResourceManager.GetString("message_deleted_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not fetch ban reason..
        /// </summary>
        internal static string user_banned_error {
            get {
                return ResourceManager.GetString("user_banned_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User banned..
        /// </summary>
        internal static string user_banned_text {
            get {
                return ResourceManager.GetString("user_banned_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} &lt;@{1}&gt; was banned. \n **Reason:** {2}.
        /// </summary>
        internal static string user_banned_title {
            get {
                return ResourceManager.GetString("user_banned_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} &lt;@{1}&gt; joined. \n **Account Age:** {2}.
        /// </summary>
        internal static string user_joined_text {
            get {
                return ResourceManager.GetString("user_joined_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User joined..
        /// </summary>
        internal static string user_joined_title {
            get {
                return ResourceManager.GetString("user_joined_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \n **Time Spent: {0}..
        /// </summary>
        internal static string user_left_duration {
            get {
                return ResourceManager.GetString("user_left_duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} &lt;@{1}&gt; left..
        /// </summary>
        internal static string user_left_text {
            get {
                return ResourceManager.GetString("user_left_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User left..
        /// </summary>
        internal static string user_left_title {
            get {
                return ResourceManager.GetString("user_left_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to years..
        /// </summary>
        internal static string years {
            get {
                return ResourceManager.GetString("years", resourceCulture);
            }
        }
    }
}
